### ISSUE TITLE
[Issue] Vaults have Dungeon Placeholder Doors

### ISSUE THREAD

**Issue by TheonlyTazz** [ImplementsLegend/VaultFaster#4]
### Modpack

Vaulthunters 3rd Edition

### Modpack version

3.15.1.3

### Mod Version

2.0.0

### Describe the bug

Upon generating a Vault, most (if not all) Vault Dungeon Doors are placeholders

### Steps to reproduce

1. Add Vaultfaster to Vaulthunters
2. Open Vault
3. Search Vault Dungeon
4. Find Placeholder

### Expected behaviour

Dungeons to be properly generated

### Screenshots

![image](https://github.com/user-attachments/assets/2621aae2-6335-4b56-820a-8b3b7b47760f)

**Comment by ImplementsLegend** [comment]
It's a known issue. If it happens, use `/the_vault reloadcfg gen` and go to another vault. It may be fixed in the newest version 2.0.3.1, but it needs more testing.
