### ISSUE TITLE
Spawners replaced with `the_vault:error_block`

### ISSUE THREAD

**Issue by PINPAL** [ImplementsLegend/VaultFaster#7]
![2024-08-21_21 42 55](https://github.com/user-attachments/assets/3eb6830d-3c8f-4d15-a75f-ad8a522af3c1)
![2024-08-21_21 42 25](https://github.com/user-attachments/assets/6262d3e4-ec48-4f8d-adfd-0dc10072e77d)
![2024-08-21_21 41 48](https://github.com/user-attachments/assets/389c45d9-631c-44ec-95f0-79fbede55a5d)

Happens only in certain themes, only spawners with hoard mobs are generated correctly.
Vault Seed in screenshots: `154202795459351`

**Comment by JoshWannaPaas** [comment]
This doesn't look like an error with VFaster. This was a spawner bug in one of the updates for u15 which changed turtles to levishrooms. This was fixed in newer versions of the pack. It's a config issue so if you're on the latest version you need to fix your configs.
