### ISSUE TITLE
Server Crashing on Load with VaultFaster

### ISSUE THREAD

**Issue by Cooldude1123** [ImplementsLegend/VaultFaster#9]
Just did a fresh reinstall of VH3's latest server files and deleted all the old configs. I made sure to grab the latest versions of the Vault Mod, Vault Integrations, and Vault Faster, just in case. With Vault Faster in the mod folder the server crashes with:
> VaultIntegrations (vaultintegrations) encountered an error during the common_setup event phase §7java.lang.NoClassDefFoundError: Could not initialize class iskallia.vault.config.Config

Not sure why the errors are for Vault Mod and Vault Integrations, but without Vault Faster the server starts and runs just fine. 

Here's the crash report:
[crash-2024-09-25_15.08.47-fml.txt](https://github.com/user-attachments/files/17137557/crash-2024-09-25_15.08.47-fml.txt)

and the server log:
[2024-09-25-1.log](https://github.com/user-attachments/files/17137561/2024-09-25-1.log)

**Comment by ImplementsLegend** [comment]
did you install KotlinForForge?

**Comment by Cooldude1123** [comment]
I did not. I Should have looked at the Curse dependencies and/or that this was written using Kotlin here on GitHub. Thanks btw, the server seems to be starting up just fine now. Excited to see the performance increase I'll hopefully get.
